### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by aaronjanse** [PotatoParser/vinyl#1]
Cool project!

I tried to download the following URL: https://www.youtube.com/watch?v=32az2CLr6bo

I saw a popup saying "illegal request." The dev tools network tab shows https://vinyl-livid.now.sh/meta returning 403 forbidden with the following response body:
```json
{"error":"Illegal Request.https://vinyl-web.com/"}
```

Cheers!

**Comment by PotatoParser** [comment]
Are you accessing the website on [https://vinyl-livid.now.sh](https://vinyl-livid.now.sh)? There is a same-site referer header protection on the current website.

**Comment by aaronjanse** [comment]
> Are you accessing the website on https://vinyl-livid.now.sh? 

I am. The error is now "Incorrect Referer."

**Comment by PotatoParser** [comment]
Oh yikes, you'll have to use [http://vinyl-web.com/](http://vinyl-web.com/)

**Comment by aaronjanse** [comment]
In that case, I recommend updating the link at the top of the repo front page

**Comment by PotatoParser** [comment]
I didn’t realize that Vercel updates that link, thanks for the catch!!!
