### ISSUE TITLE
Unable to find video

### ISSUE THREAD

**Issue by Fernsicles** [PotatoParser/vinyl#9]
![image](https://user-images.githubusercontent.com/22437119/100294101-9c310900-2f3a-11eb-89d3-9b9f069a3d98.png)
It broke

**Comment by PotatoParser** [comment]
Thanks for this! I'll look into it soon! It looks like ytdl needs to be update.

**Comment by PotatoParser** [comment]
Fixed by https://github.com/PotatoParser/vinyl/commit/077eb3da6431e56180a4000d278c2da1ad648646
